### ISSUE TITLE
Failed to Parse Spot header

### ISSUE THREAD

**Issue by Rubman86** [Spottarr/Spottarr#13]
After first installation system just hangs while retrieving the initial spot list
error code:
`Failed to parse spot header:`

<img width="672" alt="Image" src="https://github.com/user-attachments/assets/d21643c3-4a6e-41f2-a9b5-609901a4aee4" />

**Comment by christiaanderidder** [comment]
Hi @Rubman86,

This error is logged when the import encounters invalid values from the spotnet usenet groups.
The application does not log anything for successful imports besides the import start/end date, so it might look like it's hanging while actually synchronizing.
The values logged do indeed not look like valid values, so it's expected that they can't be parsed, it's interesting to see where they come from though.

Would you be able to provide some additional information:
- Docker command and/or docker compose file used (make sure to remove any sensitive credentials)
- Any environment variable overrides used to configure Spottarr
- Are you specifying a custom value for `SPOTNET__RETRIEVEAFTER`, if so, what value?

**Comment by Rubman86** [comment]
Hello Christiaan (of gewoon hallo ;-) )

Here my Compose file it's running on a Synology DS718+
I added a mem_limit afterwards since it looked like this was an added issue due to the errors and effectively halting my NAS.
```
---
services:
  spottarr:
    image: ghcr.io/spottarr/spottarr:latest
    container_name: spottarr
    mem_limit: 2g
    environment:
      - USENET__HOSTNAME=newsserver
      - USENET__USERNAME=user
      - USENET__PASSWORD=pass
      - USENET__PORT=563
      - USENET__USETLS=true
      - USENET__MAXCONNECTIONS=30
      - SPOTNET__RETRIEVEAFTER=2010-11-11T00:00:00Z
    volumes:
      - /volume1/docker/spottarr/data:/data
    ports:
      - 8383:8383
    restart: unless-stopped
```
I tried different ports, and retrieveafter settings but all of them come to the same result.
Only thing I didn't try was not changing the retrieve after, but I want it to find older spots as well.
