### ISSUE TITLE
UNIQUE constraint failed en Header date is not in the correct format

### ISSUE THREAD

**Issue by Aesculapius** [Spottarr/Spottarr#37]
Installatie binnen portainer met docker-compose verliep prima. 
Alleen het ophalen van de index gaat op twee plekken fout:

12:17:15 fail: Spottarr.Services.SpotImportService[359457455] Failed to save spots. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Spots.MessageId'.    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)    at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken) --- End of stack trace from previous location ---    at EFCore.BulkExtensions.SqlAdapters.Sqlite.SqliteAdapter.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)    at EFCore.BulkExtensions.SqlAdapters.Sqlite.SqliteAdapter.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)    at EFCore.BulkExtensions.SqlAdapters.Sqlite.SqliteAdapter.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)    at EFCore.BulkExtensions.SqlBulkOperation.InsertAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)    at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)    at Spottarr.Services.SpotImportService.FetchAndSaveSpots(UsenetOptions usenetOptions, IReadOnlyList`1 spots, CancellationToken cancellationToken) in /src/src/Spottarr.Services/SpotImportService.cs:line 155

en

12:17:16 fail: Quartz.Core.JobRunShell[0] Job DEFAULT.import-spots threw an unhandled Exception:  System.AggregateException: One or more errors occurred. (Header date is not in the correct format)  ---> System.FormatException: Header date is not in the correct format    at Usenet.Nntp.Parsers.HeaderDateParser.Parse(String value)    at Spottarr.Services.Parsers.HeaderDateParser.Parse(String value) in /src/src/Spottarr.Services/Parsers/HeaderDateParser.cs:line 9    at Spottarr.Services.Parsers.NntpHeaderParser.Parse(String header) in /src/src/Spottarr.Services/Parsers/NntpHeaderParser.cs:line 17    at Spottarr.Services.SpotImportService.ParseSpotHeader(String header, ConcurrentBag`1 spots, DateTimeOffset retrieveAfter, Boolean importAdultContent) in /src/src/Spottarr.Services/SpotImportService.cs:line 340    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) --- End of stack trace from previous location ---    at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)    at System.Threading.Tasks.TaskReplicator.Replica.Execute()    --- End of inner exception stack trace ---    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)    at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally) --- End of stack trace from previous location ---    at System.Threading.Tasks.Parallel.ForWorker[TLocal,TInt](TInt fromInclusive, TInt toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)    at Spottarr.Services.SpotImportService.FetchSpotHeaders(SpotnetOptions options, NntpArticleRange batch) in /src/src/Spottarr.Services/SpotImportService.cs:line 320    at Spottarr.Services.SpotImportService.Import(SpotnetOptions spotnetOptions, UsenetOptions usenetOptions, IReadOnlyList`1 articleRanges, CancellationToken cancellationToken) in /src/src/Spottarr.Services/SpotImportService.cs:line 111    at Spottarr.Services.SpotImportService.Import(CancellationToken cancellationToken) in /src/src/Spottarr.Services/SpotImportService.cs:line 95    at Spottarr.Services.Jobs.ImportSpotsJob.Execute(IJobExecutionContext context) in /src/src/Spottarr.Services/Jobs/ImportSpotsJob.cs:line 24    at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)

Lijkt op deze: https://github.com/Spottarr/Spottarr/issues/24

Maar ik heb hem net gebouwd dus laatste versie (1.3.0)

Docker-compose (Portainer):
```
services:
  spottarr:
    image: ghcr.io/spottarr/spottarr:latest
    container_name: spotarr
    user: 1004:1004 # Make sure to set the correct UID and GID for your system
    environment:
      - PUID=1004
      - PGID=1004
      - "USENET__HOSTNAME=reader.i-telligent.com"
      - "USENET__USERNAME=<removed>"@i-telligent.com"
      - "USENET__PASSWORD=<removed>"
      - "USENET__PORT=563"
      - "USENET__USETLS=true"
      - "USENET__MAXCONNECTIONS=10"
      - "SPOTNET__RETRIEVEAFTER=2024-05-01T00:00:00Z"
      - "SPOTNET__IMPORTBATCHSIZE=10000"
      - "SPOTNET__RETENTIONDAYS=365" # Use 0 for unlimited
      - "SPOTNET__IMPORTADULTCONTENT=false"
    volumes:
      - /srv/spotarr/config:/data
    ports:
      - 8383:8383
    restart: unless-stopped
    networks:
      - media
      
networks:
  media:
    external: true

```
