### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by sanderquirynen** [Spottarr/Spottarr#59]
I'm having trouble getting the docker container up and running.

When I run docker compose, I see this error:
```spottarr     | 18:49:21 info: Microsoft.Extensions.Hosting.IHost[15242847] Database migration started [/data/spottarr.db].
spottarr     | 18:49:51 fail: Microsoft.EntityFrameworkCore.Database.Command[20102] Failed executing DbCommand (30,050ms) [Parameters=[], CommandType='Text', CommandTimeou );  "Timestamp" TEXT NOT NULLSTRAINT "PK___EFMigrationsLock" PRIMARY KEY,
spottarr     | Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
spottarr     |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
spottarr     |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
spottarr     |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
spottarr     |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
spottarr     |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
spottarr     |    at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
spottarr     | --- End of stack trace from previous location ---
spottarr     |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
spottarr     |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
spottarr     |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
spottarr     |    at Microsoft.EntityFrameworkCore.Sqlite.Migrations.Internal.SqliteHistoryRepository.AcquireDatabaseLockAsync(CancellationToken cancellationToken)
spottarr     |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
spottarr     |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
spottarr     |    at Spottarr.Data.Helpers.HostExtensions.MigrateDatabase(IHost host) in /src/src/Spottarr.Data/Helpers/HostExtensions.cs:line 20
spottarr     |    at Spottarr.Data.Helpers.HostExtensions.MigrateDatabase(IHost host) in /src/src/Spottarr.Data/Helpers/HostExtensions.cs:line 21
spottarr     |    at Program.<Main>$(String[] args) in /src/src/Spottarr.Web/Program.cs:line 18
spottarr     |    at Program.<Main>(String[] args)
spottarr exited with code 139
```

I'm using this config:
```
spottarr:
    image: ghcr.io/spottarr/spottarr:latest
    container_name: spottarr
    user: 1000:1000 # Make sure to set the correct UID and GID for your system
    environment:
      - USENET__HOSTNAME=*******
      - USENET__USERNAME=*******
      - USENET__PASSWORD=*******
      - USENET__PORT=563
      - USENET__USETLS=true
      - USENET__MAXCONNECTIONS=10
      - SPOTNET__RETRIEVEAFTER=2024-10-01T00:00:00Z
      - SPOTNET__IMPORTBATCHSIZE=10000
      - SPOTNET__RETENTIONDAYS=365 # Use 0 for unlimited
      - SPOTNET__IMPORTADULTCONTENT=false
    volumes:
      - ./spottarr:/config
      - /data:/data
    ports:
      - 8383:8383
    restart: unless-stopped
    networks:
      servarrnetwork:
        ipv4_address: 172.39.0.5
```

The rest of my *Arr stack uses pretty much this config setup if that helps: 
https://github.com/TechHutTV/homelab/blob/main/media/compose.yaml
